# This pod contains a mysql database

version: "2"

services:
  mysql:
    image: mysql:5.7.20
    container_name: local-mysql
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: root
