version: "2"

services:
  rabbit:
    container_name: local-rabbit
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user
      RABBITMQ_LOG_LEVEL: info
    network_mode: host
